version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose port 8000
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    restart: unless-stopped  # Ensure the app restarts if it crashes
    volumes:
      - .:/app  # Optional: Mount the current directory
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]  # Optional: Explicitly define the command
