version: '3.8'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose port 8000
    environment:
      - UVICORN_HOST=0.0.0.0  # Make sure your app listens on all interfaces
      - UVICORN_PORT=8000      # Set the port to match the CMD in Dockerfile
